# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Recycle Bin controller is a service controller for managing Recycle Bin resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Recycle Bin
description: |-
  Manage Amazon Recycle Bin resources in AWS from within your Kubernetes cluster.


  **About Amazon Recycle Bin**


  Recycle Bin is a data recovery feature that enables you to restore accidentally deleted Amazon EBS snapshots and EBS-backed AMIs.
  When using Recycle Bin, if your resources are deleted, they are retained in the Recycle Bin for a time period that you specify 
  before being permanently deleted.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: Rule
  spec: '{}'
maintainers:
- name: "recyclebin maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon Recycle Bin Developer Resources
  url: https://docs.aws.amazon.com/ebs/latest/userguide/recycle-bin.html
